dir=/storage/1ABE6CDDBE6CB345/Downloads/aria2
continue=true
always-resume=true
auto-file-renaming=true
file-allocation=none

input-file=/data/data/com.termux/files/home/.local/state/aria2/aria2.session
save-session=/data/data/com.termux/files/home/.local/state/aria2/aria2.session
save-session-interval=60

enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-allow-origin-all=false

max-concurrent-downloads=2
max-connection-per-server=4
split=4
min-split-size=20M
disk-cache=32M

enable-dht=true
bt-enable-lpd=true
seed-time=0

check-certificate=true
console-log-level=warn
log=/data/data/com.termux/files/home/.local/state/aria2/aria2.log
log-level=notice
