#!/data/data/com.termux/files/usr/bin/sh

set -eu

export HOME=/data/data/com.termux/files/home
export PREFIX=/data/data/com.termux/files/usr
export PATH="$PREFIX/bin:/system/bin"

secret_file="$HOME/.config/aria2/rpc.secret"
config_file="$HOME/.config/aria2/aria2.conf"

exec "$PREFIX/bin/aria2c" \
  --conf-path="$config_file" \
  --rpc-secret="$(cat "$secret_file")"
